// "Explain it to the patient": the last decision of every case. Plain words that are true, against
// the usual traps: jargon, false reassurance, blame or a promise the model cannot keep. The right
// answer is always option 0 (the runtime shuffles the order). Keyed by case id; `c` is the case handle.

const ex = (q, right, wrong, why) => ({ q, options: [right, ...wrong], answer: 0, why });

export const EXPLAIN = {
  bleed: () => ex('He asks what happened. What do you tell him?',
    'Scarring in your liver backs blood up into swollen veins in your gullet. One burst. We have closed it, and tablets and checks will lower the chance of it happening again.',
    ['You had a variceal haemorrhage from portal hypertension secondary to cirrhosis, managed with EVL and terlipressin.', 'It was a one-off. Now it is fixed you will not need any more treatment.', 'This happened because you did not come to clinic.'],
    'Plain words, the cause, what was done and what comes next. No jargon, no false reassurance, no blame.'),
  prevention: () => ex('Aisha asks why she needs treatment when she feels well. What do you say?',
    'The scarring in your liver has raised the pressure in your belly veins, so some veins in your gullet have swollen. They have not bled, and treatment now makes it much less likely they ever will.',
    ['You have large oesophageal varices, which means clinically significant portal hypertension.', 'You feel well, so the varices are not dangerous yet. We can wait.', 'If you take this tablet the varices will be gone for good.'],
    'Explain the risk she cannot feel and why prevention works, without jargon or overpromising.'),
  'new-ascites': (c) => (c.cs.heart
    ? ex('He asks why his belly is swelling. What do you say?',
      'Your heart is struggling to pump blood onward, so it backs up through your liver and leaks into your belly. Treating the heart is what will help.',
      ['You have a high SAAG, high-protein ascites from post-hepatic portal hypertension.', 'It is your liver from the drinking, so you must stop alcohol.', 'It is only water; a few taps will sort it out.'],
      'The fluid comes from the heart here. Name the real cause in plain words.')
    : ex('He asks why his belly is swelling. What do you say?',
      'Scarring in your liver has raised the pressure in the veins around it, and fluid leaks into your belly. Less salt, water tablets and stopping alcohol help the most.',
      ['You have low-protein ascites with a SAAG over 1.1 from cirrhosis.', 'It is a bit of water; it will settle on its own.', 'Your heart is failing.'],
      'Cause and what he can do, in plain words.')),
  refractory: () => ex('She asks what a TIPS would do. What do you say?',
    'A small tube placed inside the liver lets blood bypass the scarring, so the pressure falls and the fluid builds up much more slowly. It can cause confusion in some people, so we check for that first.',
    ['A TIPS is a transjugular intrahepatic portosystemic shunt that lowers the HVPG.', 'It cures the cirrhosis.', 'It has no downsides, so everyone with fluid should have one.'],
    'What it does, what it cannot do and the main risk, in plain words.'),
  gastric: () => ex('He asks why his liver is fine but he bled. What do you say?',
    'A clot has blocked the vein that drains your spleen, so blood found a detour through veins in your stomach that swelled and bled. Your liver itself is healthy.',
    ['You have sinistral portal hypertension from splenic vein thrombosis with isolated gastric varices type 2.', 'It must be your liver; the tests will show it later.', 'It was a stomach ulcer and needs no follow-up.'],
    'A blocked vein before the liver, not liver disease.'),
  'budd-chiari': () => ex('She asks why her liver is swollen. What do you say?',
    'The veins that drain blood out of your liver are blocked, so blood is backing up inside it. Blood thinners and opening the veins can help it recover.',
    ['You have Budd–Chiari syndrome with a post-sinusoidal block and a raised FHVP.', 'It is a fatty liver; lose some weight.', 'There is nothing that can be done.'],
    'The block is in the outflow; it is treatable.'),
  pvt: () => ex('The patient asks what the clot means. What do you say?',
    'A clot is blocking the main vein that brings blood from your gut to your liver. Your liver is healthy; we treat the clot and watch for swollen veins it can cause.',
    ['You have portal vein thrombosis with a cavernoma and pre-hepatic portal hypertension.', 'Your liver is failing.', 'It will dissolve by itself, so no follow-up is needed.'],
    'A blocked inflow vein, a healthy liver, and why follow-up matters.'),
  'nsbb-problem': () => ex('George asks why you stopped his tablet. What do you say?',
    'The tablet that protected your veins is now lowering your blood pressure too much, and your kidneys are suffering. We are pausing it and protecting the veins another way.',
    ['Your MAP fell below 65 with AKI, so the NSBB window has closed.', 'The tablet never worked.', 'You can stop all your tablets now.'],
    'Why the drug changed from help to harm, and that the veins are still covered.'),
  schisto: () => ex('He asks why his liver tests are normal but he has swollen veins. What do you say?',
    'A parasite has scarred the small veins at the entrance of your liver, so pressure builds before the liver. The liver itself still works well.',
    ['You have presinusoidal portal hypertension from schistosomiasis with a normal HVPG.', 'Normal liver tests mean the pressure is normal too.', 'It is cirrhosis.'],
    'A block before the liver cells; a normal liver and a normal HVPG do not rule it out.'),
  hepatofugal: () => ex('She asks what "reversed flow" means. What do you say?',
    'Your liver is stiff enough that blood in its main vein is being pushed away from it instead of into it. It is a sign of advanced scarring, so a liver specialist should see you.',
    ['You have hepatofugal portal venous flow.', 'It is a scanner error; ignore it.', 'It means you need an operation tomorrow.'],
    'What it shows and why referral matters, without alarm or dismissal.'),
  'post-tips': () => ex('His wife asks why he became confused. What do you say?',
    'The new tube lets some blood skip the liver, so toxins it would clear reach the brain. Medicine clears them, and the tube can be narrowed if it keeps happening.',
    ['He has hepatic encephalopathy from portosystemic shunting via the TIPS.', 'It is old age and nothing to do with the procedure.', 'The tube must be taken out straight away.'],
    'The cause, the fix and the fallback, in plain words.'),
  'treat-cause': () => ex('Lena asks whether she is cured. What do you say?',
    'The virus is gone, and your liver is healing: the pressure has come down. Some scarring stays, so we still check your liver every six months.',
    ['You have recompensated cirrhosis with an HVPG below 10 after SVR.', 'Yes, completely. You never need to see us again.', 'Nothing has changed; the damage is permanent.'],
    'Real improvement, and the reason follow-up continues.'),
};
