// The final-assessment bank: single-best-answer stems (five options, one line of explanation each).
// Two stems come from each of the eight cases cut from the course; the rest ask where the block is.
// `src` names the source (a case id or 'site'); `answer` is the index of the best option.

export const BANK = [
  // ── Melena with a big spleen (gastric) ──
  { id: 'gastric-1', src: 'gastric',
    stem: 'A 55-year-old man with chronic pancreatitis has melena. Endoscopy shows isolated fundal varices and no esophageal varices. The spleen is enlarged; liver tests are normal and the portal vein is patent on Doppler.',
    q: 'Where is the block?',
    options: ['Portal vein', 'Splenic vein', 'Hepatic sinusoids', 'Hepatic veins', 'Right heart'],
    answer: 1,
    explain: ['The portal vein is patent, so the block is not here.', 'Pancreatitis can clot the splenic vein; splenic blood drains through the short gastric veins into fundal varices (left-sided portal hypertension).', 'Normal liver tests and isolated fundal varices argue against cirrhosis.', 'Hepatic vein obstruction gives ascites and a big liver, not isolated gastric varices.', 'A cardiac cause raises the whole system, with ascites and raised jugular venous pressure.'] },
  { id: 'gastric-2', src: 'gastric',
    stem: 'A 55-year-old with chronic pancreatitis has bleeding gastric fundal varices. The liver is normal, the portal vein is patent and the splenic vein is occluded.',
    q: 'Most appropriate definitive treatment?',
    options: ['TIPS', 'Propranolol', 'Splenectomy or splenic artery embolisation', 'Esophageal band ligation', 'Balloon-occluded retrograde transvenous obliteration (BRTO)'],
    answer: 2,
    explain: ['Portal pressure is normal; a shunt from the portal vein does not drain a block upstream of it.', 'Beta blockers lower portal inflow but do not treat a segmental splenic vein block.', 'Removing or embolising splenic inflow empties the varices and treats the cause.', 'The varices are gastric; there are no esophageal varices to band.', 'BRTO can control gastric varices, but the definitive treatment of splenic vein thrombosis is removing splenic inflow.'] },

  // ── Rapid ascites in a young patient (budd-chiari) ──
  { id: 'bc-1', src: 'budd-chiari',
    stem: 'A 28-year-old woman on the oral contraceptive pill has 3 weeks of abdominal pain, tender hepatomegaly and ascites. Ascitic fluid: SAAG 2.0 g/dL, total protein 3.2 g/dL. Doppler shows no flow in the hepatic veins.',
    q: 'Most likely diagnosis?',
    options: ['Cirrhosis', 'Budd-Chiari syndrome', 'Portal vein thrombosis', 'Peritoneal carcinomatosis', 'Nephrotic syndrome'],
    answer: 1,
    explain: ['Cirrhosis usually gives a low ascitic protein (under 2.5 g/dL) and develops over years.', 'Hepatic vein outflow obstruction: high SAAG with high protein, a tender big liver and no hepatic venous flow.', 'Portal vein thrombosis alone rarely causes much ascites, and the hepatic veins flow normally.', 'Carcinomatosis gives a low SAAG (under 1.1 g/dL).', 'Nephrotic ascites has a low SAAG and low protein.'] },
  { id: 'bc-2', src: 'budd-chiari',
    stem: 'A 30-year-old man with Budd-Chiari syndrome and a JAK2 V617F mutation has ascites. He has been started on diuretics.',
    q: 'Best first treatment of the venous block?',
    options: ['Liver transplantation', 'TIPS', 'Surgical portocaval shunt', 'Anticoagulation', 'Measure the HVPG to stage it'],
    answer: 3,
    explain: ['Transplant is the last rung of the ladder, after the less invasive steps fail.', 'TIPS is the step after anticoagulation and angioplasty fail.', 'Surgical shunts have largely been replaced by TIPS.', 'Anticoagulate every patient first, then angioplasty or stent a short stenosis, then TIPS, then transplant.', 'The hepatic veins cannot be wedged reliably, so the HVPG misleads in Budd-Chiari syndrome.'] },

  // ── Abdominal pain and a clot (pvt) ──
  { id: 'pvt-1', src: 'pvt',
    stem: 'A 40-year-old man with no liver disease has 5 days of abdominal pain. CT shows a fresh thrombus in the portal vein extending into the superior mesenteric vein. No bowel ischaemia.',
    q: 'Best next step?',
    options: ['Anticoagulation for at least 6 months', 'TIPS', 'Beta blocker only', 'Observe; most clots resolve on their own', 'Emergency surgical thrombectomy'],
    answer: 0,
    explain: ['Early anticoagulation recanalises most acute clots and prevents spread into the mesenteric veins.', 'TIPS is reserved for failure of anticoagulation or worsening thrombosis.', 'A beta blocker does not treat the clot.', 'Untreated, the clot rarely clears and can extend to cause bowel infarction.', 'Surgery is for bowel infarction, which he does not have.'] },
  { id: 'pvt-2', src: 'pvt',
    stem: 'A 35-year-old woman has esophageal varices and splenomegaly years after neonatal umbilical catheterisation. The liver is normal on biopsy. The portal vein is replaced by a cavernoma.',
    q: 'What is her HVPG most likely to be?',
    options: ['Normal (about 3 mmHg)', '12 mmHg', '18 mmHg', '25 mmHg', 'It cannot be measured'],
    answer: 0,
    explain: ['The block is before the liver; wedged and free hepatic pressures are both normal, so the HVPG is normal although portal pressure is high.', 'A gradient this high means the block is in the sinusoids.', 'This is a cirrhotic gradient.', 'Too high for any prehepatic block.', 'It can be measured; it is simply normal.'] },

  // ── The beta blocker that became a problem (nsbb) ──
  { id: 'nsbb-1', src: 'nsbb',
    stem: 'A 62-year-old man with cirrhosis and ascites takes propranolol 80 mg twice daily for varices. Blood pressure is now 84/50 mmHg, sodium 124 mmol/L and creatinine has doubled in a week.',
    q: 'Best change to his beta blocker?',
    options: ['Increase the dose', 'Switch to carvedilol at full dose', 'Reduce or stop it', 'Add midodrine and keep the dose', 'No change; varices take priority'],
    answer: 2,
    explain: ['A higher dose would lower blood pressure and kidney perfusion further.', 'Carvedilol lowers blood pressure even more.', 'With systolic pressure under 90, sodium under 125 or acute kidney injury, reduce or stop it; restart when stable.', 'Midodrine may help, but the beta blocker still has to come down first.', 'Kidney injury with hypotension outweighs the bleeding benefit while it lasts.'] },
  { id: 'nsbb-2', src: 'nsbb',
    stem: 'A 58-year-old with cirrhosis has had his beta blocker stopped for kidney injury. Two weeks later creatinine is back to baseline and blood pressure is 112/70 mmHg. He has medium varices and has never bled.',
    q: 'Best plan for prevention of a first bleed?',
    options: ['Leave the beta blocker off; nothing else', 'Restart a beta blocker carefully, or band the varices if it is not tolerated', 'TIPS', 'Octreotide infusion', 'Repeat endoscopy in 3 years'],
    answer: 1,
    explain: ['Medium varices still need prophylaxis.', 'Once stable, restart at a low dose and titrate; band ligation is the alternative if beta blockers fail.', 'TIPS is not used for primary prophylaxis.', 'Octreotide is for acute bleeding only.', 'Medium varices need treatment now, not surveillance.'] },

  // ── Varices with a normal liver (optional: INCPH / schistosomiasis) ──
  { id: 'incph-1', src: 'optional',
    stem: 'A 32-year-old man from the Nile delta has hematemesis from esophageal varices. He has a large spleen, normal liver synthetic function and periportal fibrosis on ultrasound.',
    q: 'Where is the block?',
    options: ['Prehepatic (portal vein)', 'Presinusoidal (portal tracts)', 'Sinusoidal', 'Postsinusoidal (central veins)', 'Posthepatic (IVC)'],
    answer: 1,
    explain: ['The portal vein is open; the fibrosis sits around the portal tracts.', 'Schistosoma eggs lodge in the portal venules and cause pipestem periportal fibrosis.', 'The sinusoids are spared, so synthetic function stays normal.', 'Central veins are not involved in schistosomiasis.', 'Posthepatic blocks cause ascites and a big liver, not this picture.'] },
  { id: 'incph-2', src: 'optional',
    stem: 'A 45-year-old woman with large varices has a normal-looking liver on biopsy except for obliterated small portal venules (porto-sinusoidal vascular disorder). Her HVPG is 6 mmHg.',
    q: 'Why is the HVPG lower than expected?',
    options: ['The catheter was not wedged', 'The block is presinusoidal, so the wedged pressure does not reach it', 'Her portal pressure is truly normal', 'The varices are from a cardiac cause', 'HVPG is always below 10 in women'],
    answer: 1,
    explain: ['A poorly wedged catheter is possible, but the disease explains it.', 'The wedged pressure reflects the sinusoids; a block upstream of them leaves the HVPG low while portal pressure is high.', 'Large varices mean the portal pressure is high.', 'A cardiac cause raises free and wedged pressures together, with ascites.', 'There is no sex-specific limit.'] },

  // ── Reversed flow on a routine scan (explain) ──
  { id: 'rev-1', src: 'explain',
    stem: 'A 66-year-old with cirrhosis has a routine Doppler. Flow in the main portal vein runs away from the liver (hepatofugal). He feels well.',
    q: 'What does this finding mean?',
    options: ['A normal variant', 'Advanced portal hypertension, with portal blood escaping through collaterals', 'Portal vein thrombosis', 'Right heart failure', 'A transducer artifact that should be ignored'],
    answer: 1,
    explain: ['Portal flow is normally toward the liver (hepatopetal).', 'When intrahepatic resistance is very high, blood takes the downhill route out through collaterals.', 'A clot gives absent flow and a filling defect, not reversed flow.', 'Right heart failure gives a pulsatile portal waveform.', 'Reversal confirmed on repeat is a real and important finding.'] },
  { id: 'rev-2', src: 'explain',
    stem: 'A 50-year-old with right heart failure from tricuspid regurgitation has a Doppler of the portal vein.',
    q: 'Which portal waveform is expected?',
    options: ['Steady hepatopetal flow', 'Pulsatile flow with brief reversal in each beat', 'Persistent hepatofugal flow', 'No flow', 'Flow only in inspiration'],
    answer: 1,
    explain: ['Steady flow is normal.', 'High right atrial pressure is transmitted back through the sinusoids, so portal flow pulses with the heart.', 'Sustained reversal suggests severe intrahepatic portal hypertension.', 'Absent flow suggests thrombosis.', 'Normal flow varies a little with breathing, but this is not the expected cardiac pattern.'] },

  // ── Confused after a TIPS (tips-he) ──
  { id: 'tips-1', src: 'tips-he',
    stem: 'A 60-year-old woman, 3 months after TIPS for refractory ascites, is brought in confused with asterixis. Ascites has resolved. No fever, normal sodium.',
    q: 'Most likely cause?',
    options: ['Shunt thrombosis', 'Spontaneous bacterial peritonitis', 'Hepatic encephalopathy from portosystemic shunting', 'Hepatorenal syndrome', 'Hyponatremia'],
    answer: 2,
    explain: ['A blocked shunt brings the ascites back; hers has resolved.', 'Without ascites or fever, SBP is unlikely.', 'The shunt carries gut blood past the liver, so ammonia reaches the brain.', 'Hepatorenal syndrome follows ascites and low kidney perfusion, not a working TIPS.', 'Her sodium is normal.'] },
  { id: 'tips-2', src: 'tips-he',
    stem: 'The same woman keeps returning with overt encephalopathy despite lactulose and rifaximin. The TIPS is widely patent; portal pressure gradient 4 mmHg.',
    q: 'Best next step?',
    options: ['Widen the stent to 12 mm', 'Reduce the shunt diameter', 'Add a beta blocker', 'Stop lactulose', 'Large-volume paracentesis'],
    answer: 1,
    explain: ['A wider shunt would divert even more blood and worsen it.', 'Narrowing the shunt sends more blood back through the liver and controls refractory encephalopathy.', 'A beta blocker does not treat encephalopathy.', 'Lactulose stays; stopping it worsens confusion.', 'She has no ascites to drain.'] },

  // ── Treat the cause (treat-cause) ──
  { id: 'cause-1', src: 'treat-cause',
    stem: 'A 48-year-old man with alcohol-related cirrhosis had an HVPG of 16 mmHg. After 18 months of abstinence his ascites has gone and the repeat HVPG is 9 mmHg.',
    q: 'What explains the fall?',
    options: ['Measurement error', 'Removing the cause let fibrosis and inflammation regress, lowering intrahepatic resistance', 'A spontaneous shunt has opened', 'Portal vein thrombosis', 'His heart function has fallen'],
    answer: 1,
    explain: ['A fall this size is real.', 'Treating the cause (abstinence, viral cure) can lower the HVPG and recompensate the liver.', 'A shunt lowers portal pressure but with worse, not better, function.', 'A clot would not resolve his ascites.', 'Heart failure would raise the pressures.'] },
  { id: 'cause-2', src: 'treat-cause',
    stem: 'A 52-year-old woman with compensated hepatitis C cirrhosis achieves a sustained virological response. Pre-treatment HVPG was 14 mmHg; she has small varices.',
    q: 'What is true after cure?',
    options: ['Portal hypertension is guaranteed to disappear', 'Surveillance can stop at once', 'HVPG often falls, but clinically significant portal hypertension can persist, so follow-up continues', 'Beta blockers must be stopped', 'HVPG always rises after cure'],
    answer: 2,
    explain: ['Many patients still have a raised gradient after cure.', 'Varices and cancer risk remain; surveillance continues.', 'Cure lowers the risk, but those with significant portal hypertension stay at risk and keep follow-up.', 'Stopping beta blockers depends on reassessment, not cure alone.', 'Removing the cause lowers, not raises, the gradient.'] },

  // ── Where is the block? (site) ──
  { id: 'site-1', src: 'site',
    stem: 'A 70-year-old with constrictive pericarditis has ascites. Hepatic vein catheter: free pressure 18 mmHg, wedged 22 mmHg. Right atrial pressure 17 mmHg.',
    q: 'Where is the block?',
    options: ['Prehepatic', 'Presinusoidal', 'Sinusoidal', 'Posthepatic (IVC)', 'Cardiac'],
    answer: 4,
    explain: ['A prehepatic block leaves the hepatic pressures normal.', 'A presinusoidal block leaves the hepatic pressures normal.', 'A sinusoidal block gives a high gradient; here it is 4 mmHg.', 'An IVC block would leave the right atrial pressure low.', 'Raised free, wedged and right atrial pressures with a normal gradient point to the heart.'] },
  { id: 'site-2', src: 'site',
    stem: 'A 58-year-old with alcohol-related liver disease: free hepatic vein pressure 7 mmHg, wedged 23 mmHg.',
    q: 'Where is the block?',
    options: ['Prehepatic', 'Presinusoidal', 'Sinusoidal', 'Posthepatic', 'Cardiac'],
    answer: 2,
    explain: ['A prehepatic block gives a normal gradient.', 'A presinusoidal block gives a normal or slightly raised gradient.', 'The HVPG is 16 mmHg: the resistance sits in the sinusoids, as in cirrhosis.', 'A posthepatic block raises the free pressure too.', 'A cardiac cause raises the free pressure and leaves the gradient normal.'] },
  { id: 'site-3', src: 'site',
    stem: 'A 40-year-old has ascites after a stem cell transplant with busulfan conditioning. Weight gain, tender hepatomegaly and jaundice began within 3 weeks. Hepatic veins are patent on Doppler.',
    q: 'Where is the block?',
    options: ['Portal vein', 'Portal tracts', 'Sinusoids and small central veins', 'Large hepatic veins', 'Right heart'],
    answer: 2,
    explain: ['The portal vein is not the target of the injury.', 'The portal tracts are spared.', 'Sinusoidal obstruction syndrome injures sinusoidal endothelium and occludes the small central veins; the HVPG rises.', 'The large hepatic veins are patent, unlike Budd-Chiari syndrome.', 'The heart is normal.'] },
  { id: 'site-4', src: 'site',
    stem: 'A 52-year-old has ascites and leg edema. Hepatic veins are patent but there is a membranous web in the IVC above them. Right atrial pressure is 3 mmHg.',
    q: 'Where is the block?',
    options: ['Sinusoidal', 'Presinusoidal', 'Posthepatic (IVC)', 'Cardiac', 'Prehepatic'],
    answer: 2,
    explain: ['The block is outside the liver.', 'Presinusoidal blocks do not swell the legs.', 'A web in the suprahepatic IVC blocks hepatic outflow and leg return; the right atrium stays normal.', 'A cardiac cause raises the right atrial pressure.', 'The portal vein is not blocked.'] },
  { id: 'site-5', src: 'site',
    stem: 'A patient has new ascites. Ascitic fluid: SAAG 1.6 g/dL, total protein 1.2 g/dL.',
    q: 'Most likely source?',
    options: ['Peritoneal carcinomatosis', 'Cirrhosis', 'Heart failure', 'Tuberculous peritonitis', 'Pancreatic ascites'],
    answer: 1,
    explain: ['Carcinomatosis gives a low SAAG.', 'High SAAG with low protein: sinusoidal portal hypertension with leaky, capillarised sinusoids.', 'Heart failure gives a high SAAG with high protein (2.5 g/dL or more).', 'Tuberculosis gives a low SAAG with high protein.', 'Pancreatic ascites has a low SAAG and high amylase.'] },
  { id: 'site-6', src: 'site',
    stem: 'A patient has new ascites and raised jugular venous pressure. Ascitic fluid: SAAG 1.8 g/dL, total protein 3.4 g/dL.',
    q: 'Most likely source?',
    options: ['Cirrhosis', 'Heart failure', 'Peritoneal carcinomatosis', 'Nephrotic syndrome', 'Portal vein thrombosis'],
    answer: 1,
    explain: ['Cirrhosis usually gives protein under 2.5 g/dL.', 'Raised venous pressure reaches healthy sinusoids, which leak protein-rich fluid: high SAAG, high protein.', 'Carcinomatosis gives a low SAAG.', 'Nephrotic syndrome gives a low SAAG and low protein.', 'Isolated portal vein thrombosis rarely causes ascites, and the JVP is normal.'] },
  { id: 'site-7', src: 'site',
    stem: 'A patient with portal hypertension has a normal HVPG, a normal liver on biopsy, and a large spleen. Doppler shows no flow in the portal vein and many periportal collaterals.',
    q: 'Where is the block?',
    options: ['Prehepatic', 'Sinusoidal', 'Postsinusoidal', 'Posthepatic', 'Cardiac'],
    answer: 0,
    explain: ['A blocked portal vein with a cavernoma: portal pressure is high but the HVPG is normal.', 'Sinusoidal disease raises the HVPG.', 'Postsinusoidal disease raises the HVPG.', 'A posthepatic block raises the free hepatic pressure and causes ascites.', 'The heart is normal.'] },
  { id: 'site-8', src: 'site',
    stem: 'A patient with cirrhosis has an HVPG of 11 mmHg and no varices on endoscopy.',
    q: 'How is his portal hypertension classed?',
    options: ['Normal', 'Mild, not yet clinically significant', 'Clinically significant portal hypertension', 'Only significant once varices appear', 'Cannot be classed without a portal vein pressure'],
    answer: 2,
    explain: ['A normal HVPG is 1 to 5 mmHg.', 'Mild portal hypertension is 6 to 9 mmHg.', 'At 10 mmHg or more, decompensation and varices become likely: clinically significant.', 'The gradient defines it; varices are a consequence.', 'The HVPG is the accepted surrogate for portal pressure in sinusoidal disease.'] },
  { id: 'site-9', src: 'site',
    stem: 'A TIPS is placed for recurrent variceal bleeding. Before: portal vein 30 mmHg, IVC 8 mmHg. After: portal vein 17 mmHg, IVC 10 mmHg.',
    q: 'Is the portal pressure gradient on target?',
    options: ['No; it is 22 mmHg', 'Yes; it is 7 mmHg, under the 12 mmHg target', 'No; it should be under 3 mmHg', 'Yes, but only because the portal pressure is under 20', 'It cannot be judged without the HVPG'],
    answer: 1,
    explain: ['22 mmHg was the gradient before the shunt.', 'PPG = portal vein minus IVC = 7 mmHg; under 12 mmHg protects against rebleeding.', 'Lowering it that far raises the risk of encephalopathy and heart strain.', 'The target is the gradient, not the absolute portal pressure.', 'After TIPS the gradient is measured directly across the shunt.'] },

  { id: 'site-10', src: 'site',
    stem: 'A 34-year-old woman with polycythaemia vera has ascites and an enlarged caudate lobe. During an HVPG study the catheter cannot enter the hepatic veins, and venography shows a spider-web pattern of collaterals.',
    q: 'Where is the block?',
    options: ['Sinusoidal', 'Large hepatic veins (posthepatic)', 'Portal vein', 'Right heart', 'Portal tracts'],
    answer: 1,
    explain: ['Sinusoidal disease leaves the hepatic veins open to the catheter.', 'Budd-Chiari syndrome: the hepatic veins are occluded; the caudate lobe drains directly to the IVC and enlarges.', 'A portal vein block leaves the hepatic veins normal.', 'A cardiac cause leaves the hepatic veins open and raises right atrial pressure.', 'A presinusoidal block leaves the hepatic veins normal.'] },

  // ── Clinic stems from the course units (a mixed exam needs these too) ──
  { id: 'clin-1', src: 'prevention',
    stem: 'A 45-year-old man with compensated cirrhosis has large varices on a screening endoscopy and has never bled. HVPG 14 mmHg.',
    q: 'Best next step?',
    options: ['Start carvedilol', 'Band ligation now', 'TIPS', 'Octreotide', 'Repeat endoscopy in a year'],
    answer: 0,
    explain: ['A non-selective beta blocker (carvedilol preferred) lowers the gradient and prevents a first bleed and decompensation.', 'Banding is the alternative if beta blockers are not tolerated or contraindicated.', 'TIPS is not for primary prophylaxis.', 'Octreotide is for acute bleeding only.', 'Large varices need treatment now.'] },
  { id: 'clin-2', src: 'bleed',
    stem: 'A man with cirrhosis vomits blood. Pulse 118, BP 92/60 mmHg, hemoglobin 8.2 g/dL. Octreotide and ceftriaxone have been started.',
    q: 'Best transfusion strategy?',
    options: ['Transfuse to hemoglobin 10 to 12 g/dL', 'Transfuse when hemoglobin falls below 7 g/dL, aiming for 7 to 9', 'Give fresh frozen plasma to correct the INR first', 'Give platelets regardless of count', 'Avoid all blood products'],
    answer: 1,
    explain: ['Over-transfusion raises portal pressure and causes rebleeding.', 'A restrictive threshold lowers rebleeding and death in variceal bleeding.', 'The INR does not reflect bleeding risk in cirrhosis; plasma expands volume and raises portal pressure.', 'Platelets are not given routinely.', 'Blood is given when hemoglobin falls under 7 g/dL or with massive bleeding.'] },
  { id: 'clin-3', src: 'new-ascites',
    stem: 'A man with cirrhotic ascites has abdominal pain and mild confusion. Ascitic fluid: neutrophils 410 /mm³, culture pending.',
    q: 'Best next step?',
    options: ['Wait for the culture', 'Start a third-generation cephalosporin and give albumin', 'Large-volume paracentesis alone', 'Start a beta blocker', 'Surgical laparotomy'],
    answer: 1,
    explain: ['Neutrophils of 250 /mm³ or more diagnose SBP; do not wait.', 'Treat SBP at once; albumin on days 1 and 3 lowers the risk of kidney injury and death.', 'Draining does not treat the infection.', 'A beta blocker does not treat infection and may harm kidney perfusion now.', 'Surgery is for secondary peritonitis (several organisms, very high protein), not this.'] },
  { id: 'clin-4', src: 'refractory',
    stem: 'A woman with cirrhosis has tense ascites despite spironolactone 400 mg and furosemide 160 mg daily with a low-salt diet. A paracentesis removes 8 L.',
    q: 'Best plan for the fluid removed?',
    options: ['No replacement needed', 'Give albumin, about 8 g per litre removed', 'Give 2 L of normal saline', 'Give fresh frozen plasma', 'Raise the diuretic doses further'],
    answer: 1,
    explain: ['Removing more than 5 L without albumin risks circulatory dysfunction and kidney injury.', 'Albumin (6 to 8 g per litre removed) protects the circulation after large-volume paracentesis.', 'Saline is a poorer volume expander here and adds sodium.', 'Plasma is not a volume expander for this purpose.', 'Her ascites is refractory: maximal doses have failed; next consider TIPS.'] },
];
