// Generated by scripts/snapshots.mjs from the model; do not edit. Settled mean pressures (mmHg)
// along PATH for every patient, with HVPG, portal pressure, portal flow (L/min) and ascites (L).
export const PATH = [["INT","Gut"],["SMV","SMV"],["CONF","Portal v."],["SIN_R","Sinusoids"],["CV_R","Central v."],["RHV","Hepatic v."],["IVCS","IVC"],["RA","RA"]];
export const SNAPSHOTS = {
  "healthy":{"P":[12,9,7.8,7,4.8,4.1,3.5,3],"hvpg":2.4,"pv":7.8,"pvFlow":1.1,"ascites":0},
  "postprandial":{"P":[13.6,10,8.5,7.5,4.9,4.1,3.4,2.8],"hvpg":2.9,"pv":8.5,"pvFlow":1.41,"ascites":0},
  "pvt-acute":{"P":[21.5,20.1,19.6,5.7,3.5,2.8,2.2,1.6],"hvpg":2.4,"pv":19.6,"pvFlow":0,"ascites":0},
  "pvt-chronic":{"P":[22.8,20.3,19.4,7.8,5.9,5.3,4.8,4.3],"hvpg":2.1,"pv":19.4,"pvFlow":0,"ascites":0},
  "svt":{"P":[11.1,8.1,6.9,6.4,4.4,3.7,3.2,2.7],"hvpg":2.3,"pv":6.9,"pvFlow":0.66,"ascites":0},
  "schisto":{"P":[23.3,20.8,20,7.6,5.8,5.2,4.7,4.2],"hvpg":2,"pv":20,"pvFlow":0.87,"ascites":0},
  "cirr-comp":{"P":[15.7,13.1,12.1,11.1,5.4,4.1,3.5,3],"hvpg":6.5,"pv":12.1,"pvFlow":1.14,"ascites":0},
  "csph":{"P":[21.2,18.7,17.8,16.8,6.2,4.9,4.3,3.8],"hvpg":11.6,"pv":17.8,"pvFlow":1.14,"ascites":0},
  "cirr-decomp":{"P":[26,23.5,22.8,22.4,6.6,5.6,5.3,4.7],"hvpg":16.7,"pv":22.8,"pvFlow":0.66,"ascites":0.7},
  "cirr-hepatofugal":{"P":[20,17.6,16.6,16.9,5.2,4.6,4.5,3.9],"hvpg":12.3,"pv":16.6,"pvFlow":-0.66,"ascites":0},
  "gastric-varix":{"P":[26.2,23.7,23,22.7,6.5,5.6,5.3,4.8],"hvpg":17.1,"pv":23,"pvFlow":0.53,"ascites":0.5},
  "sos":{"P":[16.8,14.4,13.5,12.8,11.5,3.6,3.1,2.6],"hvpg":8.9,"pv":13.5,"pvFlow":1.05,"ascites":0.7},
  "budd-chiari":{"P":[30,27.4,26.4,26,25.5,25.5,3.7,3.3],"hvpg":0.4,"pv":26.4,"pvFlow":0.62,"ascites":7.7},
  "ivc-web":{"P":[20.2,18.1,17.3,16.7,15.8,15.6,15.2,2.9],"hvpg":0.9,"pv":17.3,"pvFlow":1,"ascites":2.6},
  "rhf":{"P":[22.6,21.1,20.6,20.2,19.6,19.5,19.2,19],"hvpg":0.6,"pv":20.6,"pvFlow":0.68,"ascites":5.5},
  "constrictive":{"P":[14.9,13.3,12.7,12.3,11.3,11,10.7,10.5],"hvpg":1.1,"pv":12.7,"pvFlow":0.66,"ascites":0.4},
};
