// Generated by scripts/snapshots.mjs from the model; do not edit. Settled mean pressures (mmHg)
// along PATH for every patient, with HVPG, portal pressure, portal flow (L/min) and ascites (L).
export const PATH = [["INT","Gut"],["SMV","SMV"],["CONF","Portal v."],["SIN_R","Sinusoids"],["CV_R","Central v."],["RHV","Hepatic v."],["IVCS","IVC"],["RA","RA"]];
export const SNAPSHOTS = {
  "healthy":{"P":[12,9,7.8,7,4.8,4.1,3.5,3],"hvpg":2.4,"pv":7.8,"pvFlow":1.1,"ascites":0},
  "postprandial":{"P":[13.6,10,8.5,7.5,4.9,4.1,3.4,2.8],"hvpg":2.9,"pv":8.5,"pvFlow":1.41,"ascites":0},
  "pvt-acute":{"P":[21.7,20.3,19.8,5.7,3.5,2.8,2.2,1.6],"hvpg":2.5,"pv":19.8,"pvFlow":0,"ascites":0},
  "pvt-chronic":{"P":[23.2,20.7,19.8,7.9,6,5.4,4.8,4.3],"hvpg":2.2,"pv":19.8,"pvFlow":0,"ascites":0},
  "svt":{"P":[11.3,8.4,7.2,6.5,4.4,3.7,3.1,2.6],"hvpg":2.4,"pv":7.2,"pvFlow":0.87,"ascites":0},
  "schisto":{"P":[24,21.5,20.8,7.7,5.9,5.3,4.8,4.3],"hvpg":2,"pv":20.8,"pvFlow":0.97,"ascites":0},
  "cirr-comp":{"P":[15.7,13.1,12.1,11.1,5.4,4.1,3.5,3],"hvpg":6.5,"pv":12.1,"pvFlow":1.14,"ascites":0},
  "csph":{"P":[21.6,19.1,18.2,17.2,6.3,5,4.4,3.9],"hvpg":11.8,"pv":18.2,"pvFlow":1.2,"ascites":0.1},
  "cirr-decomp":{"P":[26.4,23.9,23.2,22.8,6.8,5.7,5.4,4.8],"hvpg":17,"pv":23.2,"pvFlow":0.74,"ascites":0.9},
  "cirr-hepatofugal":{"P":[20,17.6,16.6,16.9,5.2,4.6,4.5,3.9],"hvpg":12.3,"pv":16.6,"pvFlow":-0.66,"ascites":0},
  "gastric-varix":{"P":[21.2,18.6,17.7,17.6,5.7,4.8,4.5,4],"hvpg":12.6,"pv":17.7,"pvFlow":0.06,"ascites":0.6},
  "sos":{"P":[16.8,14.4,13.5,12.8,11.5,3.6,3.1,2.6],"hvpg":9,"pv":13.5,"pvFlow":1.06,"ascites":0.7},
  "budd-chiari":{"P":[29.2,26.9,26,25.6,25.2,25.2,4.1,3.6],"hvpg":0.4,"pv":26,"pvFlow":0.54,"ascites":7.6},
  "ivc-web":{"P":[12.3,10.9,10.3,10,8.8,8.5,8.2,-1.3],"hvpg":1.2,"pv":10.3,"pvFlow":0.55,"ascites":0},
  "rhf":{"P":[22.6,21.1,20.6,20.2,19.6,19.5,19.2,19],"hvpg":0.6,"pv":20.6,"pvFlow":0.68,"ascites":5.5},
  "constrictive":{"P":[14.9,13.3,12.7,12.3,11.3,11,10.7,10.5],"hvpg":1.1,"pv":12.7,"pvFlow":0.66,"ascites":0.4},
};
