// Generated by scripts/snapshots.mjs from the model; do not edit. Settled mean pressures (mmHg)
// along PATH for every patient, with HVPG, portal pressure, portal flow (L/min) and ascites (L).
export const PATH = [["INT","Gut"],["SMV","SMV"],["CONF","Portal v."],["SIN_R","Sinusoids"],["CV_R","Central v."],["RHV","Hepatic v."],["IVCS","IVC"],["RA","RA"]];
export const SNAPSHOTS = {
  "healthy":{"P":[12,9,7.8,7,4.8,4.1,3.5,3],"hvpg":2.4,"pv":7.8,"pvFlow":1.1,"ascites":0,"fp":{"pv":7.8,"whvp":6.5,"fhvp":4.1,"ra":3,"hvpg":2.4,"asc":0,"saag":2.3,"tp":2.9,"lsm":5}},
  "postprandial":{"P":[13.6,10,8.5,7.5,4.9,4.1,3.4,2.8],"hvpg":2.9,"pv":8.5,"pvFlow":1.41,"ascites":0,"fp":{"pv":8.5,"whvp":7,"fhvp":4.1,"ra":2.8,"hvpg":2.9,"asc":0,"saag":2.2,"tp":3,"lsm":5}},
  "pvt-acute":{"P":[21.7,20.3,19.9,5.7,3.5,2.8,2.2,1.6],"hvpg":2.5,"pv":19.9,"pvFlow":0,"ascites":0,"fp":{"pv":19.9,"whvp":5.2,"fhvp":2.8,"ra":1.6,"hvpg":2.5,"asc":0,"saag":2.8,"tp":2,"lsm":5}},
  "pvt-chronic":{"P":[23.2,20.7,19.8,8,6,5.4,4.8,4.3],"hvpg":2.2,"pv":19.8,"pvFlow":0,"ascites":0,"fp":{"pv":19.8,"whvp":7.6,"fhvp":5.4,"ra":4.3,"hvpg":2.2,"asc":0,"saag":2.7,"tp":2.2,"lsm":5}},
  "svt":{"P":[11.1,8.1,6.9,6.4,4.4,3.7,3.2,2.7],"hvpg":2.3,"pv":6.9,"pvFlow":0.66,"ascites":0,"fp":{"pv":6.9,"whvp":6,"fhvp":3.7,"ra":2.7,"hvpg":2.3,"asc":0,"saag":2.4,"tp":2.8,"lsm":5}},
  "schisto":{"P":[24,21.5,20.8,7.7,5.9,5.3,4.8,4.3],"hvpg":2,"pv":20.8,"pvFlow":0.97,"ascites":0,"fp":{"pv":20.8,"whvp":7.3,"fhvp":5.3,"ra":4.3,"hvpg":2,"asc":0,"saag":2.8,"tp":2.1,"lsm":5}},
  "cirr-comp":{"P":[15.7,13.1,12.1,11.1,5.4,4.1,3.6,3],"hvpg":6.5,"pv":12.1,"pvFlow":1.14,"ascites":0,"fp":{"pv":12.1,"whvp":10.6,"fhvp":4.1,"ra":3,"hvpg":6.5,"asc":0,"saag":2.2,"tp":3.1,"lsm":12.7}},
  "csph":{"P":[21.7,19.1,18.2,17.2,6.3,5,4.4,3.9],"hvpg":11.8,"pv":18.2,"pvFlow":1.2,"ascites":0.1,"fp":{"pv":18.2,"whvp":16.8,"fhvp":5,"ra":3.9,"hvpg":11.8,"asc":121,"saag":2.5,"tp":2.7,"lsm":24.4}},
  "cirr-decomp":{"P":[26.3,23.7,23.1,22.6,6.8,5.8,5.5,4.9],"hvpg":16.7,"pv":23.1,"pvFlow":0.74,"ascites":1,"fp":{"pv":23.1,"whvp":22.5,"fhvp":5.8,"ra":4.9,"hvpg":16.7,"asc":965,"saag":1.9,"tp":1.8,"lsm":28.6}},
  "cirr-hepatofugal":{"P":[20.4,17.9,17,17.3,5.3,4.7,4.6,4],"hvpg":12.5,"pv":17,"pvFlow":-0.64,"ascites":0.5,"fp":{"pv":17,"whvp":17.2,"fhvp":4.7,"ra":4,"hvpg":12.5,"asc":514,"saag":2,"tp":1.4,"lsm":25.2}},
  "gastric-varix":{"P":[26.2,23.7,23,22.7,6.5,5.6,5.3,4.8],"hvpg":17.1,"pv":23,"pvFlow":0.53,"ascites":0.5,"fp":{"pv":23,"whvp":22.7,"fhvp":5.6,"ra":4.8,"hvpg":17.1,"asc":522,"saag":1.9,"tp":2.2,"lsm":28.9}},
  "sos":{"P":[16.8,14.4,13.5,12.8,11.5,3.6,3.1,2.6],"hvpg":8.9,"pv":13.5,"pvFlow":1.06,"ascites":0.7,"fp":{"pv":13.5,"whvp":12.5,"fhvp":3.6,"ra":2.6,"hvpg":8.9,"asc":683,"saag":1.5,"tp":4.2,"lsm":18.1}},
  "budd-chiari":{"P":[30.3,27.7,26.7,26.2,25.7,25.7,3.8,3.4],"hvpg":0.4,"pv":26.7,"pvFlow":0.64,"ascites":7.8,"fp":{"pv":26.7,"whvp":26.1,"fhvp":25.7,"ra":3.4,"hvpg":0.4,"asc":7794,"saag":1.4,"tp":4.3,"lsm":44.5}},
  "ivc-web":{"P":[20.2,18.1,17.3,16.7,15.8,15.6,15.2,2.9],"hvpg":0.9,"pv":17.3,"pvFlow":1,"ascites":2.6,"fp":{"pv":17.3,"whvp":16.5,"fhvp":15.6,"ra":2.9,"hvpg":0.9,"asc":2579,"saag":1.4,"tp":4.3,"lsm":24.2}},
  "rhf":{"P":[22.6,21.1,20.6,20.2,19.6,19.5,19.2,19],"hvpg":0.6,"pv":20.6,"pvFlow":0.68,"ascites":5.5,"fp":{"pv":20.6,"whvp":20.1,"fhvp":19.5,"ra":19,"hvpg":0.6,"asc":5526,"saag":1.4,"tp":4.3,"lsm":32}},
  "constrictive":{"P":[14.9,13.3,12.7,12.3,11.3,11,10.7,10.5],"hvpg":1.1,"pv":12.7,"pvFlow":0.66,"ascites":0.4,"fp":{"pv":12.7,"whvp":12.1,"fhvp":11,"ra":10.5,"hvpg":1.1,"asc":401,"saag":1.5,"tp":4.1,"lsm":15}},
};
