// Presenter talk: Doppler of the portal system (Core). Slide fields as documented at the top of decks.js.

const mi = (x) => `<mi>${x}</mi>`, mo = (x) => `<mo>${x}</mo>`;

export const DOPPLER = {
  id: 'doppler', level: 'core', title: 'Doppler of the portal system', minutes: 12,
  objectives: [
    'Read normal portal and hepatic vein Doppler: direction, velocity and waveform.',
    'Recognise slow and reversed portal flow in cirrhosis.',
    'Tell portal vein thrombosis, Budd–Chiari syndrome and heart failure apart on Doppler.',
    'Know what a patent TIPS looks like.',
  ],
  summary: 'What the Doppler probe reads in the portal and hepatic veins: normal flow, cirrhosis, reversal, thrombosis, Budd–Chiari, heart failure and a TIPS. Ends with a comparison table.',
  slides: [
    {
      id: 'probe', preset: 'healthy', cam: 'portal', labels: ['SMV', 'SV', 'CONF'], tool: { kind: 'doppler', vessel: 'PV_TRUNK' },
      kicker: 'Doppler', title: 'What the probe measures',
      eq: [mi('Q') + mo('=') + '<mover><mi>v</mi><mo>¯</mo></mover>' + mo('×') + mi('A'), 'Q flow · v̄ mean velocity · A cross-sectional area of the vein'],
      line: 'The velocity of blood in the main portal vein. Normally 15 to 40 cm/s, steady, and toward the liver (hepatopetal).',
      notes: 'The probe sends ultrasound into the vein and reads the frequency shift of the echoes from moving red cells. The spectrum plots velocity against time: above the baseline is flow toward the probe, which for the portal vein is toward the liver. Normal portal flow is hepatopetal, monophasic with gentle respiratory phasicity, with a mean velocity of about 15 to 40 cm/s. Velocity times the cross-sectional area gives flow, about 1 L a minute in health. The angle of insonation should be under 60 degrees, or the velocity is misread.',
      ask: ['Which way does normal portal flow run, and how fast?', 'Toward the liver (hepatopetal), at about 15 to 40 cm/s.'],
    },
    {
      id: 'hepatic', cam: 'hepatic', labels: ['RHV', 'RA'], tool: { kind: 'doppler', vessel: 'RHV_IVC' },
      kicker: 'Doppler', title: 'The hepatic vein waveform',
      line: 'Flow runs toward the heart and pulses with the right atrium: two forward waves and a brief reversal with each beat.',
      notes: 'The hepatic veins are close to the right atrium, so their waveform follows it. The normal pattern is triphasic: the a wave (atrial contraction) briefly reverses flow, then the S and D waves carry blood toward the heart during ventricular systole and diastole. A stiff, cirrhotic liver damps the wave to biphasic or monophasic. A tall a wave and S-wave reversal point to tricuspid regurgitation or a high right atrial pressure.',
      ask: ['What causes the brief reversal in the normal hepatic vein waveform?', 'Atrial contraction (the a wave).'],
    },
    {
      // (The same 8-day fall in splanchnic tone as the Circuit talk's meal, as a time-lapse from fasting.)
      id: 'meal', days: 8, ramp: { splanchnicTone: [1, 0.72] }, lapse: { seconds: 6, from: 'Fasting', to: 'After a meal' },
      cam: 'portal', labels: ['SMV', 'CONF'], tool: { kind: 'doppler', vessel: 'PV_TRUNK' },
      data: 'tiles', tiles: ['pvFlow', 'pv'], key: ['pvFlow'], delta: true,
      kicker: 'Doppler', title: 'After a meal',
      line: 'Portal flow and velocity rise by about a quarter. The pressure barely moves.',
      notes: 'Digestion dilates the gut arterioles and portal flow rises by a quarter to a half, peaking 30 to 60 minutes after eating. A normal liver takes the extra flow with little rise in pressure. Portal Doppler should be done fasting, or the velocity is overestimated and slow flow in early cirrhosis is missed. Liver stiffness also rises after a meal, which is why FibroScan is done fasting too.',
      ask: ['Why is portal Doppler done fasting?', 'A meal raises portal flow and velocity, which can hide the slow flow of portal hypertension.'],
    },
    {
      id: 'slow', preset: 'cirr-decomp', cam: 'portal', labels: ['CONF'], tool: { kind: 'doppler', vessel: 'PV_TRUNK' },
      data: 'tiles', tiles: ['hvpg', 'pv'], key: ['hvpg'],
      kicker: 'Cirrhosis', site: 'sin', title: 'Cirrhosis slows the portal vein',
      line: 'Resistance in the sinusoids slows portal flow. A mean velocity under 15 cm/s is abnormal.',
      notes: 'As intrahepatic resistance rises, portal velocity falls and the vein widens (a main portal vein over 13 mm is a soft sign). The congestion index, cross-sectional area over mean velocity, rises above 0.07 cm·s. These signs are specific but insensitive: a normal Doppler does not exclude clinically significant portal hypertension. Splenomegaly, collaterals and reversed flow in the paraumbilical vein add to the picture.',
      ask: ['What portal vein velocity is abnormal?', 'A mean velocity under 15 cm/s.'],
    },
    {
      id: 'reverse', preset: 'cirr-hepatofugal', cam: 'portal', labels: ['CONF'], tool: { kind: 'doppler', vessel: 'PV_TRUNK' },
      data: 'tiles', tiles: ['pvFlow', 'hvpg'], key: ['pvFlow'],
      kicker: 'Cirrhosis', site: 'sin', title: 'Flow reverses',
      line: 'When the collaterals drain more than the liver accepts, portal flow turns away from the liver (hepatofugal). The spectrum falls below the baseline.',
      notes: 'Hepatofugal flow appears in advanced cirrhosis, usually with large spontaneous shunts. The liver then depends on the hepatic artery. It is a sign of advanced disease, raises the risk of portal vein thrombosis and of encephalopathy, and is a warning before TIPS. To-and-fro flow is the step before full reversal.',
      ask: ['What does hepatofugal portal flow mean?', 'Portal blood runs away from the liver, out through collaterals: advanced portal hypertension.'],
    },
    {
      id: 'clot', preset: 'pvt-acute', cam: 'portal', labels: ['CONF'], mark: { edges: ['PV_TRUNK'], label: 'Clot' }, tool: { kind: 'doppler', vessel: 'PV_TRUNK' },
      data: 'tiles', tiles: ['pv', 'hvpg'], key: ['pv'],
      kicker: 'Portal vein thrombosis', site: 'pvt', title: 'Thrombosis: no signal',
      line: 'No flow in the lumen. The finding is the absence of a trace.',
      notes: 'Doppler ultrasound is the first test for portal vein thrombosis: echogenic material in the lumen with no colour or spectral signal. An acute clot may be nearly anechoic, so the missing flow signal matters more than the grey-scale picture. CT or MR then shows how far the clot extends into the splenic and mesenteric veins. The HVPG stays normal because the block lies before the liver.',
      ask: ['What is the first test for portal vein thrombosis?', 'Doppler ultrasound: no flow signal in the portal vein.'],
    },
    {
      id: 'smv', preset: 'pvt-chronic', cam: 'portal', labels: ['SMV', 'CONF'], mark: { edges: ['PV_TRUNK'], label: 'Clot' }, tool: { kind: 'doppler', vessel: 'SMV_CONF' },
      data: 'tiles', tiles: ['pv', 'varix'], key: ['pv'],
      kicker: 'Portal vein thrombosis', site: 'pvt', title: 'Chronic thrombosis: flow goes around',
      line: 'The trunk stays silent, while the mesenteric vein still flows. Its blood leaves through collaterals around the clot.',
      notes: 'Over weeks, small veins around the occluded trunk enlarge into a portal cavernoma: a tangle of serpiginous channels with slow, hepatopetal flow at the porta hepatis. The model does not draw a cavernoma, so here the flow continues in the superior mesenteric vein and leaves through portosystemic collaterals. Varices form even though the liver is normal.',
      ask: ['What is a portal cavernoma?', 'A network of collateral veins that bypasses a chronically occluded portal vein.'],
    },
    {
      id: 'bc', preset: 'budd-chiari', cam: 'hepatic', labels: ['RHV', 'RA'], mark: { edges: ['RHV_IVC', 'MHV_IVC', 'LHV_IVC'], label: 'Blocked hepatic veins' },
      tool: { kind: 'doppler', vessel: 'RHV_IVC' },
      kicker: 'Budd–Chiari syndrome', site: 'post', title: 'Budd–Chiari: the hepatic veins are silent',
      line: 'No flow in the hepatic veins, while the portal vein still fills the liver. The block is on the way out.',
      notes: 'Doppler is also the first test for Budd–Chiari syndrome: absent, reversed or flat flow in the hepatic veins, intrahepatic collaterals (spider-web veins) and a large caudate lobe. The portal vein slows and may reverse. It is the mirror image of portal vein thrombosis: there the inflow is blocked and the hepatic veins are normal.',
      ask: ['How does Doppler tell Budd–Chiari syndrome from portal vein thrombosis?', 'In Budd–Chiari the hepatic veins have no flow; in portal vein thrombosis the portal vein has none.'],
    },
    {
      id: 'rhf', preset: 'rhf', cam: 'route', labels: ['CONF', 'RHV', 'RA'], tool: { kind: 'doppler', vessel: 'PV_TRUNK' },
      data: 'tiles', tiles: ['pv', 'hvpg'], key: ['pv'],
      kicker: 'Heart failure', site: 'cardiac', title: 'Heart failure: the portal vein pulses',
      line: 'Right atrial pressure reaches back through the sinusoids to the portal vein, which now pulses with the heart.',
      notes: 'In right heart failure, tricuspid regurgitation and constrictive pericarditis, the high right atrial pressure crosses the sinusoids and the portal vein becomes pulsatile; with severe tricuspid regurgitation flow may reverse in systole. A pulsatility index over 0.5 is abnormal. A dilated IVC and hepatic veins point to the heart, not the liver. The HVPG is normal because wedged and free pressures rise together.',
      ask: ['A pulsatile portal vein and a dilated IVC: where is the problem?', 'In the heart: a high right atrial pressure transmitted back to the liver.'],
    },
    {
      id: 'tips', preset: 'cirr-decomp', params: { tips: { on: true } }, cam: 'liver', mark: { edges: ['TIPS'], label: 'Covered stent' }, tool: { kind: 'doppler', vessel: 'TIPS' },
      data: 'tiles', tiles: ['ppg'], key: ['ppg'],
      kicker: 'After TIPS', site: 'sin', title: 'TIPS: fast flow in the stent',
      line: 'Brisk flow from the portal vein to the hepatic vein means the stent is open. Under about 50 or over 250 cm/s suggests narrowing; no signal means a clot.',
      notes: 'Doppler is the surveillance test after TIPS: a baseline study in the first days, then when symptoms return. Velocities along the stent are typically 90 to 190 cm/s. A low velocity, a large change from the baseline study, or new hepatopetal flow in the intrahepatic portal branches suggest stenosis. Covered stents narrow far less often than the old bare stents. After TIPS the portal vein velocity rises and the intrahepatic portal branches often reverse toward the stent, which is expected.',
      ask: ['What Doppler finding suggests a TIPS is narrowing?', 'A stent velocity under about 50 cm/s, or a large change from the baseline study.'],
    },
    {
      id: 'summary', visual: 'table', cols: ['pv', 'hvpg', 'ppg'], asc: false, note: 'Portal flow', rowHead: 'Patient',
      of: [{ id: 'probe', kicker: 'Reference', title: 'Healthy', note: 'Toward the liver', ref: true }, { id: 'slow', title: 'Cirrhosis', note: 'Slow' },
        { id: 'reverse', title: 'Advanced cirrhosis', note: 'Reversed' }, { id: 'clot', title: 'Portal vein thrombosis', note: 'None in the portal vein' },
        { id: 'bc', title: 'Budd–Chiari', note: 'None in the hepatic veins' }, { id: 'rhf', title: 'Right heart failure', note: 'Pulsatile' }, { id: 'tips', title: 'TIPS', note: 'Fast in the stent' }],
      kicker: 'Summary', title: 'Doppler compared',
      notes: 'The Doppler places the problem before, in or after the liver, often before any pressure is measured. No flow in the portal vein: thrombosis. Slow or reversed portal flow: cirrhosis. No flow in the hepatic veins: Budd–Chiari. A pulsing portal vein: the heart.',
      ask: ['A patient has no flow in the hepatic veins and slow portal flow. What is the diagnosis?', 'Budd–Chiari syndrome.'],
    },
  ],
};
