// Presenter talk: sites and causes of portal hypertension (the slide fields are described at the top of decks.js).

const SIX = ['pvt', 'presin', 'sin', 'postsin', 'post', 'cardiac'];   // the six levels of portal hypertension, one patient each

export const SITES = {
  id: 'sites', level: 'core', title: 'Sites and causes of portal hypertension', minutes: 15,
  summary: 'Six levels of block, each with its pressure ladder and HVPG. Ends with a comparison table.',
  sections: [['Portal hypertension', ['Portal hypertension', 'Reference']], ['Before the liver', ['Pre-hepatic']], ['In the liver', ['Intrahepatic · presinusoidal', 'Intrahepatic · sinusoidal', 'Intrahepatic · postsinusoidal']], ['After the liver', ['Post-hepatic', 'Cardiac']], ['Telling them apart', ['How to tell them apart']]],
  objectives: ['Place a cause of portal hypertension at one of six levels', 'Predict the HVPG for a block at each level', 'Read a pressure ladder to find where the largest drop is'],
  slides: [
    {
      id: 'overview', preset: 'healthy', cam: 'fit', labels: ['CONF', 'SIN_R', 'RHV', 'RA'], rail: 'all',
      kicker: 'Portal hypertension', title: 'Classifying portal hypertension by site',
      line: 'Blood runs from the gut through the liver to the heart. Obstruction at any point raises the pressure upstream of it.',
      notes: 'Portal hypertension is named for the level of the block. Two levels lie before the sinusoids (pre-hepatic and presinusoidal), one is the sinusoids themselves, and three come after them (postsinusoidal, post-hepatic and cardiac). The level decides which pressures rise, what HVPG shows, whether varices form and whether ascites follows. Portal hypertension is a portal pressure gradient above 5 mmHg; 10 mmHg or more is clinically significant.',
      ask: ['Name one cause of portal hypertension at each level.', 'Portal vein thrombosis; schistosomiasis; cirrhosis; sinusoidal obstruction syndrome; Budd–Chiari syndrome; right heart failure.'],
    },
    {
      id: 'healthy', cam: 'route', labels: ['CONF', 'SIN_R', 'RHV', 'RA'], data: 'ladder', key: ['hvpg'],
      kicker: 'Reference', title: 'A healthy liver',
      line: 'Four stations: [portal vein](pv) {pv}, [sinusoids](sin) (wedged) {whvp}, [hepatic vein](fhvp) (free) {fhvp}, [right atrium](ra) {ra}. HVPG {hvpg} is normal.',
      notes: 'The wedged hepatic venous pressure (WHVP) is taken with a balloon catheter wedged in a hepatic vein: with the flow stopped, the still column of blood reads the sinusoidal pressure. The free hepatic venous pressure (FHVP) is taken with the balloon down. HVPG = WHVP − FHVP. Normal is 1 to 5 mmHg; above 5 is portal hypertension; 10 or more is clinically significant (varices, decompensation); at 12 or more varices can bleed. The portal pressure gradient (PPG) is the portal vein minus the IVC, measured directly.',
      ask: ['What does the wedged pressure measure?', 'The sinusoidal pressure: with the vein occluded, the still column of blood reads the pressure upstream.'],
    },
    {
      id: 'pvt', preset: 'pvt-chronic', cam: 'portal', labels: ['CONF', 'SV'], terms: { 'portal pressure': 'pv' }, mark: { edges: ['PV_TRUNK'], label: 'Clot' },
      data: 'ladder', key: ['hvpg', 'ppg'], rail: true, quiz: 'Where is the obstruction?',
      kicker: 'Pre-hepatic', site: 'pre', title: 'Portal vein thrombosis',
      line: 'Portal pressure is high, yet the wedged pressure and HVPG are normal because the hepatic vein catheter sits downstream of the clot.',
      causes: ['Cirrhosis', 'Myeloproliferative neoplasm, thrombophilia', 'Pancreatitis, abdominal sepsis', 'Liver or pancreatic cancer'],
      notes: 'Chronic thrombosis turns the portal vein into a cavernoma: a web of small collaterals around the occluded trunk that still carries portal blood to the liver. The liver itself is normal, so its function is preserved and ascites is uncommon, while varices and a large spleen are common. Doppler ultrasound or CT shows the clot or the cavernoma. HVPG is normal because the wedged catheter reads the sinusoids, downstream of the clot; the portal pressure gradient (PPG) is high.',
      ask: ['Why is HVPG normal when the portal pressure is about 20 mmHg?', 'The wedge reads the sinusoids, which lie downstream of the clot and are at normal pressure.'],
    },
    {
      id: 'presin', terms: { 'portal venules': 'lobule:triad' }, preset: 'schisto', cam: 'lobule:triad', data: 'ladder', key: ['pv', 'hvpg', 'ppg'], callout: { at: 'triad', label: 'Block: portal venules' }, rail: true, quiz: 'Where is the obstruction?',
      kicker: 'Intrahepatic · presinusoidal', site: 'presin', title: 'Schistosomiasis',
      line: 'Eggs lodge in the portal venules and cause periportal fibrosis. The obstruction is upstream of the sinusoids, so HVPG stays near normal.',
      causes: ['Schistosomiasis', 'Porto-sinusoidal vascular disorder', 'Early primary biliary cholangitis', 'Sarcoidosis, congenital hepatic fibrosis'],
      notes: 'Schistosoma mansoni and japonicum eggs reach the presinusoidal portal venules, where granulomas form and periportal (Symmers) fibrosis follows. The sinusoids and liver cells are spared: liver function is preserved, ascites is rare and liver stiffness is near normal. The portal vein is open on imaging, which separates it from a portal vein clot. HVPG is normal or mildly raised and underestimates the portal pressure.',
      ask: ['A patient bleeds from varices. HVPG is normal and the portal vein is open. Where is the block?', 'Presinusoidal, in the portal tracts: schistosomiasis or porto-sinusoidal vascular disorder.'],
    },
    {
      id: 'sin', terms: { sinusoids: 'lobule:sinusoid' }, preset: 'cirr-decomp', cam: 'lobule:sinusoid', callout: { at: 'sin', label: 'Block: sinusoids' }, data: 'ladder', key: ['whvp', 'hvpg'], rail: true, quiz: 'Where is the obstruction?',
      kicker: 'Intrahepatic · sinusoidal', site: 'sin', title: 'Cirrhosis',
      line: 'Fibrosis, nodules and stellate cell contraction narrow the sinusoids. The wedged pressure reflects sinusoidal pressure, so HVPG rises with portal pressure.',
      causes: ['Alcohol', 'Fatty liver disease (MASLD)', 'Hepatitis B and C', 'Autoimmune, cholestatic, metabolic'],
      notes: 'In cirrhosis the resistance is in the sinusoids: fibrosis, regenerative nodules, a capillarized endothelium and contracted stellate cells, the dynamic part that drugs can relax. Splanchnic vasodilation then raises portal inflow and sustains the pressure. The wedged pressure closely tracks the portal pressure, so HVPG estimates the portal gradient: 10 mmHg or more is clinically significant portal hypertension, and at 12 or more varices can bleed.',
      ask: ['Why does the wedged pressure track the portal pressure in cirrhosis?', 'The resistance lies in the sinusoids the wedge reads, so the wedged pressure rises with the portal pressure.'],
    },
    {
      id: 'postsin', terms: { 'central veins': 'lobule:central' }, preset: 'sos', cam: 'lobule:central', callout: { at: 'cv', label: 'Block: central venules' }, data: 'ladder', key: ['whvp', 'hvpg'], rail: true, quiz: 'Where is the obstruction?',
      kicker: 'Intrahepatic · postsinusoidal', site: 'postsin', title: 'Sinusoidal obstruction syndrome',
      line: 'Damaged endothelium obstructs the sinusoids and small central veins, upstream of the catheter tip, so the wedged pressure and HVPG rise.',
      causes: ['Conditioning for stem cell transplant', 'Oxaliplatin', 'Pyrrolizidine alkaloids (bush teas)'],
      notes: 'Formerly veno-occlusive disease. Toxic injury sheds sinusoidal endothelial cells, which obstruct the sinusoids and the terminal hepatic venules. It presents within weeks of myeloablative conditioning with tender hepatomegaly, weight gain, ascites and jaundice. An HVPG above 10 mmHg, measured with a transjugular biopsy, strongly supports the diagnosis. The model shows an earlier stage, with an HVPG of about 9 mmHg: raised, but under 10.',
      ask: ['Why does HVPG rise here but not in schistosomiasis?', 'Here the block is in the sinusoids and central venules the wedge reads; in schistosomiasis it is in the portal tracts, upstream of them.'],
    },
    {
      id: 'post', preset: 'budd-chiari', cam: 'hepatic', labels: ['RHV', 'RA'], mark: { edges: ['RHV_IVC', 'MHV_IVC', 'LHV_IVC'], label: 'Blocked hepatic veins' },
      data: 'ladder', key: ['fhvp', 'ra', 'hvpg'], rail: true, quiz: 'Where is the obstruction?',
      kicker: 'Post-hepatic', site: 'post', title: 'Budd–Chiari syndrome',
      line: 'Hepatic venous outflow is blocked. Wedged and free pressures are both high behind the block, so HVPG is near zero while the [right atrium](ra) stays normal at {ra}.',
      causes: ['Myeloproliferative neoplasm (JAK2)', 'Thrombophilia, pregnancy, the pill', 'IVC web', 'Tumor invading the veins'],
      notes: 'Hepatic venous outflow obstruction, anywhere from the small hepatic veins to the IVC at the right atrium. The liver is congested and enlarged; the caudate lobe, which drains straight into the IVC, hypertrophies. Ascites is common, protein-rich (2.5 g/dL or more) and with a SAAG of 1.1 or more. In practice the blocked veins often cannot be catheterized; when one can be entered, both readings lie behind the block. The model shows the pressures there. Doppler ultrasound, CT or MR venography make the diagnosis.',
      ask: ['Why is HVPG near zero although the portal pressure is about 26 mmHg?', 'Both the wedged and the free pressures are measured behind the block, so both are high and their difference is small.'],
    },
    {
      id: 'cardiac', preset: 'rhf', cam: 'heart', labels: ['RHV', 'IVCS', 'RA'], glow: ['ivc', 'hv'], glowSeq: 550,
      data: 'ladder', key: ['fhvp', 'hvpg', 'ppg'], rail: true, quiz: 'Where is the obstruction?',
      kicker: 'Cardiac', site: 'cardiac', title: 'Right heart failure',
      line: 'Raised [right atrial pressure](ra) is transmitted back through the hepatic veins to the sinusoids. All stations rise together and HVPG stays normal.',
      causes: ['Tricuspid regurgitation', 'Pulmonary hypertension', 'Left heart failure', 'Constrictive pericarditis'],
      notes: 'Congestive hepatopathy. The jugular venous pressure is raised, the hepatojugular reflux is positive and Doppler shows a pulsatile portal vein. The ascites is protein-rich with a SAAG of 1.1 or more. Varices are rare: they need a gradient between the portal and the systemic veins, and here both are high, so the PPG is normal. Constrictive pericarditis gives the same pattern with a normal-sized heart.',
      ask: ['Why are varices rare in heart failure despite a portal pressure of about 20 mmHg?', 'Varices need a portal-to-systemic gradient; the systemic veins are high too, so the gradient (PPG) is normal.'],
    },
    {
      id: 'ladders', cam: 'fit', visual: 'ladders', of: SIX,
      kicker: 'How to tell them apart', title: 'The largest pressure drop locates the obstruction',
      line: 'Portal pressure is high at every site. HVPG reads only the drop across the sinusoids.',
      notes: 'Read each ladder from left to right. Pre-hepatic and presinusoidal: the fall is between the portal vein and the wedge, so HVPG is normal and only a direct portal pressure (or the PPG) shows it. Sinusoidal and postsinusoidal: the fall is between the wedged and the free pressures, exactly what HVPG measures. Post-hepatic: the fall is between the free hepatic vein and the right atrium. Cardiac: there is no fall at all; every station is high.',
      ask: ['Which two levels raise the HVPG?', 'Sinusoidal and postsinusoidal.'],
    },
    {
      id: 'summary', visual: 'table', cols: ['pv', 'whvp', 'fhvp', 'ra', 'hvpg', 'ppg'], asc: true, of: [{ preset: 'healthy', kicker: 'Reference', title: 'Healthy', ref: true }, ...SIX],
      kicker: 'Summary', title: 'The six sites compared',
      line: 'Portal pressure is high at every site. HVPG rises only when the block lies between the wedge and the free hepatic vein.',
      notes: 'Portal pressure is high at every level. HVPG is raised only when the block lies between the wedge and the free hepatic vein (sinusoidal, postsinusoidal). A SAAG of 1.1 or more confirms portal hypertension as the cause of ascites; the ascites protein then separates cirrhosis (low, under 2.5 g/dL) from hepatic vein and heart disease (high). Pre-hepatic and presinusoidal disease rarely cause ascites, because the sinusoids, where ascites starts, are at normal pressure. The model gives sinusoidal obstruction syndrome a protein-rich ascites; reports in patients vary.',
      ask: ['A patient has ascites with a SAAG of 1.6 and protein of 4 g/dL. Which levels fit?', 'Post-hepatic or cardiac (Budd–Chiari, heart failure); sinusoidal obstruction syndrome too.'],
    },
  ],
};
