// Presenter talk: lowering portal pressure (the slide fields are described at the top of decks.js).

export const TREATMENT = {
  id: 'treatment', level: 'advanced', title: 'Lowering portal pressure', minutes: 14,
  sections: [['The patient', ['Lowering portal pressure']], ['Drugs', ['Non-selective beta-blocker', 'Acute variceal bleeding', 'Hepatorenal syndrome']], ['Endoscopy and TIPS', ['Endoscopy', 'Shunt', 'After TIPS']], ['Compared', ['Compared']]],
  summary: 'Propranolol, carvedilol, octreotide, terlipressin, band ligation and TIPS in one patient with decompensated cirrhosis, with the effect of each on HVPG, varices and ascites, and the cost of TIPS to liver perfusion.',
  objectives: ['Explain how each drug lowers portal pressure: inflow, resistance or both', 'Outline the treatment of an acute variceal bleed', 'Compare banding, drugs and TIPS for pressure, varices and ascites', 'Weigh the costs of TIPS: liver perfusion and encephalopathy'],
  slides: [
    {
      id: 'target', preset: 'cirr-decomp', cam: 'route', labels: ['CONF', 'SIN_R', 'RHV', 'RA'], data: 'ladder', key: ['hvpg'], tiles: ['hvpg', 'varix'],
      kicker: 'Lowering portal pressure', site: 'sin', title: 'A patient with decompensated cirrhosis',
      line: 'This patient has an HVPG of {hvpg}, large varices and ascites. Treatment lowers the inflow or the resistance, or bypasses the liver.',
      notes: 'Portal pressure is flow times resistance. Non-selective beta-blockers and the vasoactive drugs used in bleeding cut the inflow; carvedilol also lowers the resistance inside the liver; TIPS goes around it. Banding treats the varix, not the pressure. Removing the cause (stopping alcohol, treating hepatitis) lowers the resistance over months to years. On drugs, the aim is an HVPG fall of 20% or more, or to below 12 mmHg.',
      ask: ['Name a treatment that cuts the inflow and one that lowers the resistance.', 'Inflow: propranolol, octreotide, terlipressin. Resistance: carvedilol, treating the cause; TIPS goes around it.'],
    },
    {
      id: 'prop', params: { drugs: { propranolol: true } }, cam: 'portal', labels: ['SMV', 'CONF'], data: 'ladder', key: ['pv', 'hvpg'], tiles: ['hvpg', 'varix'], delta: 'target',
      kicker: 'Non-selective beta-blocker', site: 'sin', title: 'Propranolol',
      line: 'β1 blockade lowers cardiac output; β2 blockade removes the dilating tone on the gut arterioles, so they constrict. Portal inflow falls to {pvFlow}, and HVPG with it.',
      notes: 'Propranolol (or nadolol) is titrated to a resting heart rate of 55 to 60 a minute, keeping systolic pressure above 90 mmHg. It prevents a first bleed from large varices and, with banding, a second one. About a third to a half of patients reach a protective fall in HVPG. In refractory ascites with low blood pressure or kidney injury the dose is reduced or stopped. The model shows a modest fall.',
      ask: ['How is propranolol titrated?', 'To a resting heart rate of 55 to 60 a minute, keeping systolic pressure above 90 mmHg.'],
    },
    {
      id: 'carv', params: { drugs: { propranolol: false, carvedilol: true } }, cam: 'liver', glow: ['liver'],
      compare: [{ label: 'Propranolol', params: { drugs: { propranolol: true, carvedilol: false } } }, { label: 'Carvedilol', own: true, params: { drugs: { propranolol: false, carvedilol: true } } }], data: 'ladder', key: ['whvp', 'hvpg'], tiles: ['hvpg', 'varix'], delta: 'target',
      kicker: 'Non-selective beta-blocker', site: 'sin', title: 'Carvedilol',
      line: 'It also blocks α1 receptors, so the stellate cells and portal venules relax and the intrahepatic resistance falls. HVPG falls further, at some cost in blood pressure.',
      notes: 'Carvedilol 6.25 to 12.5 mg a day. Its α1 blockade relaxes the contracted stellate cells and lowers the resistance inside the liver, so it lowers HVPG more than propranolol and brings about half of propranolol non-responders to a protective fall. Baveno VII recommends a non-selective beta-blocker, preferably carvedilol, in compensated cirrhosis with clinically significant portal hypertension, to prevent decompensation. Watch the blood pressure, especially with ascites.',
      ask: ['Why does carvedilol lower HVPG more than propranolol?', 'Its α1 blockade also lowers the vascular resistance inside the liver.'],
    },
    {
      id: 'oct', params: { drugs: { carvedilol: false, octreotide: true } }, cam: 'portal', labels: ['SMV', 'CONF'], data: 'ladder', key: ['pv'], tiles: ['hvpg', 'pvFlow'], delta: 'target',
      kicker: 'Acute variceal bleeding', site: 'sin', title: 'Octreotide',
      line: 'A somatostatin analogue that blocks the gut\'s vasodilating peptides, so splanchnic inflow falls to {pvFlow} and the portal pressure with it. Start it as soon as a variceal bleed is suspected.',
      notes: 'Suspected variceal bleeding: octreotide at once (a 50 µg bolus, then 50 µg an hour), continued for 2 to 5 days; ceftriaxone; restrictive transfusion to a hemoglobin of 7 to 8 g/dL, because over-transfusion raises portal pressure; endoscopy with banding within 12 hours. Pre-emptive TIPS within 72 hours for patients at high risk: Child–Pugh C below 14 points, or B above 7 with active bleeding. Octreotide is the vasoactive drug used for bleeding in the US; elsewhere terlipressin or somatostatin are alternatives. Its effect on portal pressure is modest and partly transient, so the model gives it a smaller fall than terlipressin (splanchnic resistance × 1.35 against × 1.9), in line with HVPG studies of somatostatin analogues (Escorsell 2001, Baik 2005).',
      ask: ['Why transfuse only to a hemoglobin of 7 to 8 g/dL in a variceal bleed?', 'Extra blood volume raises portal pressure and the risk of rebleeding.'],
    },
    {
      id: 'terli', params: { drugs: { octreotide: false, terlipressin: true } }, cam: 'portal', labels: ['SMV', 'CONF'], data: 'tiles', key: ['map'], tiles: ['map', 'pvFlow', 'hvpg'], delta: 'target',
      compare: [{ label: 'Octreotide', params: { drugs: { octreotide: true, terlipressin: false } } }, { label: 'Terlipressin', own: true, params: { drugs: { octreotide: false, terlipressin: true } } }],
      kicker: 'Hepatorenal syndrome', site: 'sin', title: 'Terlipressin for HRS-AKI',
      line: 'A vasopressin analogue given with albumin. It constricts the dilated splanchnic arterioles, so blood pressure and kidney perfusion rise.',
      notes: 'In the US terlipressin is approved for hepatorenal syndrome with a rapid fall in kidney function (HRS-AKI), not for variceal bleeding. It is given with albumin (1 g/kg on day 1, then 20 to 40 g a day), as a bolus every 6 hours or a continuous infusion, and stopped if creatinine has not fallen by day 4. It is avoided with hypoxia (SpO2 below 90%), volume overload or a creatinine of 5 mg/dL or more, because of the risk of respiratory failure; other risks are ischemia and hyponatremia. Octreotide alone does little for HRS; where terlipressin is not available it is combined with midodrine and albumin, or norepinephrine is used. The model has no kidneys: the tiles show the blood pressure and portal inflow that drive kidney perfusion.',
      ask: ['What is given with terlipressin for HRS-AKI?', 'Albumin.'],
    },
    {
      id: 'band', params: { drugs: { terlipressin: false } }, action: [{ kind: 'band' }, { kind: 'band' }, { kind: 'band' }], cam: 'varices', mark: { edges: ['C1a', 'C1b'], label: 'Banded varices', kind: 'treat' },
      data: 'tiles', tiles: ['varix', 'hvpg'], key: ['varix'], delta: 'target',
      kicker: 'Endoscopy', site: 'sin', title: 'Band ligation',
      line: 'Ligated varices thrombose and shrink. With that outflow closed, HVPG rises slightly, so new varices form.',
      notes: 'Band ligation is repeated every 2 to 4 weeks until the varices are gone, followed by surveillance endoscopy. It stops an acute bleed and prevents rebleeding, but it does nothing to lower the portal pressure: the collateral closes, its flow is redirected and the pressure rises slightly (in the model, HVPG by about 1 mmHg after three bands; small studies measuring HVPG before and after eradication report rises of about 1 to 2 mmHg), so varices come back. After a bleed, banding is combined with a non-selective beta-blocker.',
      ask: ['Why combine banding with a beta-blocker after a bleed?', 'Banding removes the varices, not the high pressure that makes new ones; the beta-blocker lowers it.'],
    },
    {
      id: 'tips', params: { tips: { on: true } }, cam: 'liver', mark: { edges: ['TIPS'], label: 'Covered stent', kind: 'treat' }, data: 'ladder', key: ['pv', 'ppg'], tiles: ['ppg', 'varix'], delta: 'target',
      kicker: 'Shunt', site: 'sin', title: 'TIPS',
      line: 'A covered stent from a hepatic vein to the portal vein. Portal blood bypasses the sinusoids, and the PPG falls to {ppg}, below the {<12 mmHg} target.',
      notes: 'Transjugular intrahepatic portosystemic shunt: from the jugular vein, a needle is passed from the right hepatic vein through the liver into the right portal vein, and the tract is lined with a covered stent, usually 8 mm wide. The portal pressure gradient is measured before and after; for bleeding the aim is below 12 mmHg. Indications: pre-emptive TIPS in high-risk variceal bleeding, rescue when bleeding cannot be controlled, recurrent bleeding, and recurrent or refractory ascites.',
      ask: ['What portal pressure gradient is the aim after TIPS for bleeding?', 'Below 12 mmHg.'],
    },
    {
      id: 'after', days: 60, lapse: { seconds: 7 }, cam: 'fit', data: 'tiles', tiles: ['asc', 'sin', 'ppg'], key: ['asc'], delta: 'target',
      kicker: 'After TIPS', site: 'sin', title: 'Ascites after TIPS',
      line: 'With the sinusoids decompressed, less lymph is made and the kidneys let go of sodium. The PPG stays below {<12 mmHg}.',
      notes: 'In patients the ascites usually resolves over weeks to months after TIPS, with diuretics continued at first; the model clears it faster. Sodium excretion and kidney function improve as the effective blood volume recovers. In selected patients with recurrent ascites, TIPS improves survival compared with repeated paracentesis. The spleen may shrink a little, but low platelets often persist. The tiles compare with the patient before treatment.',
      ask: ['Name two benefits of TIPS besides stopping a bleed.', 'The ascites clears as the kidneys excrete sodium again, and the low gradient keeps varices from rebleeding.'],
    },
    {
      id: 'cost', cam: 'liver', sites: ['split'], mark: { edges: ['TIPS'], label: 'Covered stent', kind: 'treat' }, data: 'tiles', tiles: ['liver', 'shunt'], delta: 'target',
      kicker: 'After TIPS', site: 'sin', title: 'Liver perfusion and encephalopathy',
      line: 'Less portal blood reaches the sinusoids, and gut toxins pass straight into the systemic circulation. About one patient in three develops encephalopathy.',
      notes: 'After TIPS, overt hepatic encephalopathy develops in about a third of patients, mostly in the first months; older age, earlier encephalopathy and a wider stent raise the risk, and an 8 mm covered stent lowers it. The heart receives more venous return and the liver less portal blood, so TIPS is avoided in heart failure, severe pulmonary hypertension, advanced liver failure (a high MELD) and recurrent encephalopathy. Lactulose and rifaximin treat encephalopathy; the shunt can be narrowed if it persists.',
      ask: ['Name two contraindications to TIPS.', 'Heart failure or severe pulmonary hypertension; advanced liver failure (high MELD); recurrent severe encephalopathy.'],
    },
    {
      id: 'vs', cam: 'liver', data: 'ladder', key: ['ppg'], tiles: ['ppg', 'liver'], delta: 'target',
      compare: [
        { label: 'TIPS', own: true, params: { tips: { on: true }, drugs: { propranolol: false, carvedilol: false, octreotide: false, terlipressin: false } } },
        { label: 'Propranolol', params: { tips: { on: false }, drugs: { propranolol: true, carvedilol: false, octreotide: false, terlipressin: false } } },
        { label: 'Carvedilol', params: { tips: { on: false }, drugs: { propranolol: false, carvedilol: true, octreotide: false, terlipressin: false } } },
        { label: 'Octreotide', params: { tips: { on: false }, drugs: { propranolol: false, carvedilol: false, octreotide: true, terlipressin: false } } },
        { label: 'Terlipressin', params: { tips: { on: false }, drugs: { propranolol: false, carvedilol: false, octreotide: false, terlipressin: true } } },
      ],
      kicker: 'Compared', site: 'sin', title: 'TIPS against the drugs',
      line: 'Drugs lower the gradient by a few mmHg; TIPS lowers it below {<12 mmHg}, at the cost of the liver\'s portal blood.',
      notes: 'The same patient, switched between TIPS and each drug alone. In the model the drugs lower the PPG by 1 to 2 mmHg, carvedilol most; TIPS brings it below 12 mmHg but halves the blood reaching the sinusoids. The bands from the earlier slide stay in place throughout.',
      ask: ['Why does TIPS lower the gradient so much more than any drug?', 'The drugs trim the inflow or the tone; TIPS gives portal blood a low-resistance path around the sinusoids.'],
    },
    {
      id: 'summary', visual: 'table', cols: ['hvpg', 'ppg', 'varix', 'liver'], asc: false, vs: 'first', rowHead: 'Treatment', note: 'How it works',
      // (Terlipressin is left out: it treats HRS-AKI, not bleeding, and has its own slide.)
      of: [{ id: 'target', kicker: 'Baseline', title: 'Decompensated cirrhosis', note: 'HVPG 17, large varices, ascites' }, { id: 'prop', note: 'Less inflow' }, { id: 'carv', note: 'Less inflow and resistance' }, { id: 'oct', kicker: 'Vasoactive drug', note: 'Less inflow, in a bleed' },
        { id: 'band', title: 'Banding', note: 'Closes the varix, not the pressure' }, { id: 'tips', title: 'TIPS', note: 'Bypasses the liver' }, { id: 'after', kicker: 'Shunt', title: 'TIPS, 60 days on', note: 'The ascites has cleared' }],
      kicker: 'Summary', title: 'Treatments compared',
      line: 'Each treatment given alone to the same patient: the drugs trim the gradient, TIPS bypasses the resistance.',
      notes: 'Drugs cut the inflow (propranolol, octreotide, terlipressin) or the resistance as well (carvedilol). Banding eradicates varices and raises portal pressure slightly. TIPS lowers the gradient most and clears the ascites, at the price of the liver\'s portal blood and a risk of encephalopathy. In practice they combine: a beta-blocker with banding after a bleed; octreotide, banding and, for those at high risk, pre-emptive TIPS in an acute bleed.',
      ask: ['Which treatment lowers the portal pressure gradient most, and what does it cost?', 'TIPS: less blood for the liver and a risk of encephalopathy.'],
    },
  ],
};
