// Patient snapshots for Home: for every preset, the model's settled mean pressures along the
// portal pathway (gut → portal vein → sinusoids → hepatic vein → right atrium), HVPG and portal
// flow. Computed by the real engine, written to src/ui/snapshots.js; `npm test` fails if the
// file no longer matches the model (content changes must regenerate it).
//
//   node scripts/snapshots.mjs           rewrite src/ui/snapshots.js
//   node scripts/snapshots.mjs --check   exit 1 if it is out of date

import { writeFileSync, readFileSync } from 'node:fs';
import { join, dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { Engine } from '../src/engine/engine.js';
import { computeMetrics } from '../src/engine/metrics.js';
import { PRESETS } from '../src/engine/scenario.js';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = join(ROOT, 'src/ui/snapshots.js');
// The stations of the pressure profile, upstream to downstream.
export const PATH = [['INT', 'Gut'], ['SMV', 'SMV'], ['CONF', 'Portal v.'], ['SIN_R', 'Sinusoids'], ['CV_R', 'Central v.'], ['RHV', 'Hepatic v.'], ['IVCS', 'IVC'], ['RA', 'RA']];

export function snapshots() {
  const out = {};
  for (const p of PRESETS) {
    const e = new Engine();
    e.loadPreset(p.id);
    const P = e.Pf || e.P, m = computeMetrics(e);
    out[p.id] = { P: PATH.map(([n]) => Math.round(P[e.ni[n]] * 10) / 10), hvpg: Math.round(m.hvpg * 10) / 10, pv: Math.round(m.pv * 10) / 10, pvFlow: Math.round(m.pvFlow * 100) / 100, ascites: Math.round((e.slow.ascites || 0) / 100) / 10 };
  }
  return out;
}

const body = `// Generated by scripts/snapshots.mjs from the model; do not edit. Settled mean pressures (mmHg)
// along PATH for every patient, with HVPG, portal pressure, portal flow (L/min) and ascites (L).
export const PATH = ${JSON.stringify(PATH)};
export const SNAPSHOTS = ${JSON.stringify(snapshots(), null, 0).replace(/\},"/g, '},\n  "').replace(/^\{/, '{\n  ').replace(/\}$/, ',\n}')};
`;
if (process.argv.includes('--check')) {
  let cur = '';
  try { cur = readFileSync(OUT, 'utf8'); } catch { /* missing */ }
  if (cur !== body) { console.error('src/ui/snapshots.js is out of date. Run: node scripts/snapshots.mjs'); process.exit(1); }
  console.log('Snapshots are current.');
} else {
  writeFileSync(OUT, body);
  console.log('Wrote src/ui/snapshots.js');
}
